name: pytorchbearer/torchbearer
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            torch_url: torch==0.4.0 -f https://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
            torchvision_url: torchvision==0.2.0 -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 0.4.0
            pillow: pillow
            python: '3.6.15'
          - os: ubuntu-20.04
            torch_url: torch==0.4.1 -f https://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
            torchvision_url: torchvision==0.2.0 -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 0.4.1
            pillow: pillow
            python: '3.6.15'
          - os: ubuntu-20.04
            torch_url: torch==1.0.0 -f http://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
            torchvision_url: torchvision==0.2.2.post3 -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.0.0
            pillow: pillow<7.0.0
            python: '3.6.15'
          - os: ubuntu-20.04
            torch_url: torch==1.1.0 http://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
            torchvision_url: https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
            torch_version: 1.1.0
            pillow: pillow<7.0.0
            python: '3.6.15'
          - os: ubuntu-20.04
            torch_url: torch==1.2.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.2.0
            pillow: pillow<7.0.0
            python: '3.6.15'
          - os: ubuntu-20.04
            torch_url: torch==1.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.4.0
            pillow: pillow
            python: '3.6.15'
          - os: ubuntu-latest
            torch_url: torch==1.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.4.0
            pillow: pillow
            python: '3.7.17'
          - os: ubuntu-latest
            torch_url: torch==1.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.5.0
            pillow: pillow
            python: '3.7.17'
          - os: ubuntu-latest
            torch_url: torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.6.0
            pillow: pillow
            python: '3.7.17'
          - os: ubuntu-latest
            torch_url: torch==1.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.7.0
            pillow: pillow
            python: '3.7.17'
          - os: ubuntu-latest
            torch_url: torch==1.8.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.8.0
            pillow: pillow
            python: '3.7.17'
          # - os: ubuntu-latest
          #   torch_url: torch==1.9.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
          #   torchvision_url: torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          #   torch_version: 1.9.1
          #   pillow: pillow
          #   python: '3.7.17'
          - os: ubuntu-latest
            torch_url: torch==1.10.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.11.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.10.0
            pillow: pillow
            python: '3.7.17'
          - os: ubuntu-latest
            torch_url: torch==1.11.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.12.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.11.0
            pillow: pillow
            python: '3.7.17'
          - os: ubuntu-latest
            torch_url: torch==1.12.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.13.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.12.0
            pillow: pillow
            python: '3.7.17'
          - os: ubuntu-latest
            torch_url: torch==1.13.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.14.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 1.13.0
            pillow: pillow
            python: '3.7.17'
          - os: ubuntu-latest
            torch_url: torch==2.0.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.15.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 2.0.0
            pillow: pillow
            python: '3.8.18'
          - os: ubuntu-latest
            torch_url: torch==2.1.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torchvision_url: torchvision==0.16.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            torch_version: 2.1.0
            pillow: pillow
            python: '3.8.18'
    runs-on: ${{ matrix.os }}
    env:
      TORCH_URL: ${{ matrix.torch_url }}
      TORCHVISION: ${{ matrix.torchvision_url }}
      TORCH_VERSION: ${{ matrix.torch_version }}
      PILLOW: ${{ matrix.pillow }}
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v4.7.0
      with:
        python-version: ${{ matrix.python }}
    - run: echo ${{ github.sha }}_RANGE
    - run: 'if [ -z "${{ github.sha }}_RANGE"]; then COMMIT_RANGE="HEAD~..HEAD"; else COMMIT_RANGE=${{ github.sha }}_RANGE;  fi;
        '
    - run: echo $COMMIT_RANGE
    - run: |
        if ! git diff --name-only $COMMIT_RANGE | grep -qE '^(torchbearer/|tests/|.travis.yml)'
        then
          echo "Only docs were updated, not running the CI."
          exit
        fi
    - run: pip install -q coverage 
    - run: pip install -q nose
    - run: pip install -q $TORCH_URL
    - run: pip install future
    - run: pip install $PILLOW
    - run: pip install -q $TORCHVISION
    - run: pip install -q ipython
    - run: pip install -q -r requirements.txt
    - run: nosetests tests -v --with-coverage --cover-package=torchbearer
    - run: bash <(curl -s https://codecov.io/bash)
      if: "${{ success() }}"
#     # This item has no matching transformer
#     - email:
#         on_success: never
#         on_failure: always
